version: '2'

services:
  notify:
    image: docker.io/vietlong2110/notify
    environment:
      NODE_ENV: development
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    volumes:
      - ../NotifyAPI:/usr/src/app
    ports:
      - 8080:8080
  mongo:
    image: mongo
    volumes:
      - ~/docker/storage/notify-mongo:/data/db
    ports:
      - "27017:27017"
  elasticsearch:
    image: elasticsearch:alpine
    volumes:
      - ~/docker/storage/notify-elasticsearch:/var/lib/elasticsearch
    ports:
      - 9200:9200
