version: '2'

services:
  notify:
    build: .
    environment:
      NODE_ENV: development
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    ports:
      - 8080:8080
  mongo:
    image: mongo
    volumes:
      - ~/docker/storage/notify-mongo:/data/db
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.io/vietlong2110/elastic-vn
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ~/docker/storage/notify-elasticsearch:/var/lib/elasticsearch
    ports:
      - 9200:9200
