export const REQUEST_FACEBOOK_ACCESS_TOKEN = 'REQUEST_FACEBOOK_ACCESS_TOKEN';
export const RECEIVE_SERVER_DATA = 'RECEIVE_SERVER_DATA';
export const ERROR_AUTH = 'ERROR_AUTH';
export const LOGGING_OUT = 'LOGGING_OUT';
export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const LOAD_AUTH_STATE = 'LOAD_AUTH_STATE';
export const DELETE_ALL_STATES = 'DELETE_ALL_STATES';
